ml_titanic:
  target: dev
  outputs:
    dev:
      type: postgres
      host: pgml
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public 
      threads: 3 
      # search_path: ['public']
      role: postgres
      # sslmode: []
config: 
  send_anonymous_usage_stats: False
